"""
Core модуль - конфигурация, база данных, безопасность и инфраструктура.

Этот модуль предоставляет основную инфраструктуру для приложения AnkiRAG:
- Конфигурация через переменные окружения
- Асинхронная работа с PostgreSQL
- JWT аутентификация и хеширование паролей
- Структурированное логирование с поддержкой Loki
- OpenTelemetry трейсинг
- Prometheus метрики
- Middleware для обработки запросов
"""

# Config
from .config import (
    AppConfig,
    DatabaseConfig,
    EmbeddingConfig,
    JWTConfig,
    LoggingConfig,
    MetricsConfig,
    PerplexityConfig,
    RedisConfig,
    Settings,
    SopLLMConfig,
    TelemetryConfig,
    get_settings,
    settings,
)

# Database
from .database import (
    Base,
    DatabaseManager,
    close_db,
    db_manager,
    get_db,
    init_db,
)

# Dependencies
from .dependencies import (
    CurrentUserId,
    DatabaseSession,
    OptionalUserId,
    Pagination,
    PaginationParams,
    RedisClient,
    RedisManager,
    RequestId,
    TokenBlacklist,
    TokenBlacklistService,
    close_dependencies,
    get_current_user_id,
    get_optional_token,
    get_optional_user_id,
    get_redis,
    get_request_id,
    get_token,
    get_token_blacklist,
    get_token_payload,
    init_dependencies,
)

# Exceptions
from .exceptions import (
    AnkiConnectError,
    AppError,
    AuthenticationError,
    AuthorizationError,
    CardNotFoundError,
    ConflictError,
    DatabaseError,
    DeckNameExistsError,
    DeckNotFoundError,
    DocumentNotFoundError,
    DuplicateError,
    EmailAlreadyExistsError,
    ExternalServiceError,
    InvalidCredentialsError,
    InvalidInputError,
    LLMServiceError,
    NotFoundError,
    PermissionDeniedError,
    PerplexityError,
    QuotaExceededError,
    RateLimitError,
    ResourceOwnershipError,
    TokenExpiredError,
    TokenInvalidError,
    TokenRevokedError,
    TransactionError,
    UserNotFoundError,
    ValidationError,
    error_handler,
    register_exception_handlers,
    setup_exception_handlers,
)

# Logging
from .logging import (
    InterceptHandler,
    StructuredLogger,
    clear_request_context,
    get_logger,
    get_request_context,
    get_structured_logger,
    log_generation_completed,
    log_generation_failed,
    log_generation_started,
    logger,
    set_request_context,
    setup_logger,
    setup_logging,
)

# Metrics
from .metrics import (
    ACTIVE_SESSIONS,
    ANKI_CARDS_SYNCED,
    ANKI_CONNECTION_STATUS,
    ANKI_SYNC_COUNT,
    ANKI_SYNC_LATENCY,
    APP_INFO,
    AUTH_ATTEMPTS_TOTAL,
    AUTH_TOKEN_OPERATIONS,
    CARD_GENERATION_COUNT,
    CARD_GENERATION_LATENCY,
    CARDS_GENERATED,
    CARDS_REJECTED,
    DB_CONNECTION_POOL_CHECKED_OUT,
    DB_CONNECTION_POOL_OVERFLOW,
    DB_CONNECTION_POOL_SIZE,
    DB_QUERY_COUNT,
    DB_QUERY_ERRORS,
    DB_QUERY_LATENCY,
    DOCUMENT_CHUNKS_COUNT,
    DOCUMENT_PROCESSING_LATENCY,
    DOCUMENT_SIZE_BYTES,
    DOCUMENT_UPLOAD_COUNT,
    EMBEDDING_BATCH_SIZE,
    EMBEDDING_DIMENSION,
    EMBEDDING_LATENCY,
    EMBEDDING_REQUEST_COUNT,
    FACT_CHECK_CONFIDENCE,
    FACT_CHECK_COUNT,
    FACT_CHECK_LATENCY,
    FACT_CHECK_VERDICT,
    HTTP_REQUEST_COUNT,
    HTTP_REQUEST_IN_PROGRESS,
    HTTP_REQUEST_LATENCY,
    HTTP_REQUEST_SIZE_BYTES,
    HTTP_RESPONSE_SIZE_BYTES,
    JOB_COUNT,
    JOB_LATENCY,
    JOB_QUEUE_SIZE,
    JOBS_IN_PROGRESS,
    LLM_COST,
    LLM_LATENCY,
    LLM_REQUEST_COUNT,
    LLM_TOKEN_COUNT,
    REDIS_CONNECTION_POOL_SIZE,
    REDIS_OPERATION_COUNT,
    REDIS_OPERATION_LATENCY,
    REGISTRY,
    VECTOR_SEARCH_COUNT,
    VECTOR_SEARCH_LATENCY,
    VECTOR_SEARCH_RESULTS,
    counted,
    get_metrics,
    in_progress,
    init_app_info,
    init_metrics,
    metrics_endpoint,
    record_anki_sync,
    record_auth_attempt,
    record_card_generation,
    record_card_rejection,
    record_db_error,
    record_db_query,
    record_document_upload,
    record_embedding_request,
    record_fact_check,
    record_http_request,
    record_job,
    record_llm_request,
    record_redis_operation,
    record_token_operation,
    record_vector_search,
    timed,
    update_active_sessions,
    update_anki_connection_status,
    update_db_pool_metrics,
    update_job_queue_size,
    update_jobs_in_progress,
)

# Middleware
from .middleware import (
    CORSMiddleware,
    RateLimitMiddleware,
    RequestSizeLimitMiddleware,
    RequestTracingMiddleware,
    SecurityHeadersMiddleware,
    add_middleware,
    setup_middleware,
)

# Security
from .security import (
    TokenPair,
    TokenPayload,
    TokenType,
    authenticate_user,
    create_access_token,
    create_refresh_token,
    create_token,
    create_token_pair,
    decode_token,
    extract_user_id,
    hash_password,
    needs_rehash,
    verify_access_token,
    verify_password,
    verify_refresh_token,
)

# Telemetry
from .telemetry import (
    EXCLUDED_URLS,
    NoOpSpanExporter,
    SpanContext,
    TelemetryManager,
    add_span_attributes,
    add_span_event,
    get_current_span,
    get_span_id,
    get_trace_id,
    init_telemetry,
    instrument_sqlalchemy_engine,
    record_exception,
    set_span_status,
    setup_telemetry,
    shutdown_telemetry,
    telemetry_manager,
    traced,
)

__all__ = [
    # Config
    "AppConfig",
    "DatabaseConfig",
    "EmbeddingConfig",
    "JWTConfig",
    "LoggingConfig",
    "MetricsConfig",
    "PerplexityConfig",
    "RedisConfig",
    "Settings",
    "SopLLMConfig",
    "TelemetryConfig",
    "get_settings",
    "settings",
    # Database
    "Base",
    "DatabaseManager",
    "close_db",
    "db_manager",
    "get_db",
    "init_db",
    # Security
    "TokenPair",
    "TokenPayload",
    "TokenType",
    "authenticate_user",
    "create_access_token",
    "create_refresh_token",
    "create_token",
    "create_token_pair",
    "decode_token",
    "extract_user_id",
    "hash_password",
    "needs_rehash",
    "verify_access_token",
    "verify_password",
    "verify_refresh_token",
    # Exceptions
    "AnkiConnectError",
    "AppError",
    "AuthenticationError",
    "AuthorizationError",
    "CardNotFoundError",
    "ConflictError",
    "DatabaseError",
    "DeckNameExistsError",
    "DeckNotFoundError",
    "DocumentNotFoundError",
    "DuplicateError",
    "EmailAlreadyExistsError",
    "ExternalServiceError",
    "InvalidCredentialsError",
    "InvalidInputError",
    "LLMServiceError",
    "NotFoundError",
    "PermissionDeniedError",
    "PerplexityError",
    "QuotaExceededError",
    "RateLimitError",
    "ResourceOwnershipError",
    "TokenExpiredError",
    "TokenInvalidError",
    "TokenRevokedError",
    "TransactionError",
    "UserNotFoundError",
    "ValidationError",
    "error_handler",
    "register_exception_handlers",
    "setup_exception_handlers",
    # Dependencies
    "CurrentUserId",
    "DatabaseSession",
    "OptionalUserId",
    "Pagination",
    "PaginationParams",
    "RedisClient",
    "RedisManager",
    "RequestId",
    "TokenBlacklist",
    "TokenBlacklistService",
    "close_dependencies",
    "get_current_user_id",
    "get_optional_token",
    "get_optional_user_id",
    "get_redis",
    "get_request_id",
    "get_token",
    "get_token_blacklist",
    "get_token_payload",
    "init_dependencies",
    # Logging
    "InterceptHandler",
    "StructuredLogger",
    "clear_request_context",
    "get_logger",
    "get_request_context",
    "get_structured_logger",
    "logger",
    "log_generation_completed",
    "log_generation_failed",
    "log_generation_started",
    "set_request_context",
    "setup_logger",
    "setup_logging",
    # Telemetry
    "EXCLUDED_URLS",
    "NoOpSpanExporter",
    "SpanContext",
    "TelemetryManager",
    "add_span_attributes",
    "add_span_event",
    "get_current_span",
    "get_span_id",
    "get_trace_id",
    "init_telemetry",
    "instrument_sqlalchemy_engine",
    "record_exception",
    "set_span_status",
    "setup_telemetry",
    "shutdown_telemetry",
    "telemetry_manager",
    "traced",
    # Metrics
    "ACTIVE_SESSIONS",
    "ANKI_CARDS_SYNCED",
    "ANKI_CONNECTION_STATUS",
    "ANKI_SYNC_COUNT",
    "ANKI_SYNC_LATENCY",
    "APP_INFO",
    "AUTH_ATTEMPTS_TOTAL",
    "AUTH_TOKEN_OPERATIONS",
    "CARD_GENERATION_COUNT",
    "CARD_GENERATION_LATENCY",
    "CARDS_GENERATED",
    "CARDS_REJECTED",
    "DB_CONNECTION_POOL_CHECKED_OUT",
    "DB_CONNECTION_POOL_OVERFLOW",
    "DB_CONNECTION_POOL_SIZE",
    "DB_QUERY_COUNT",
    "DB_QUERY_ERRORS",
    "DB_QUERY_LATENCY",
    "DOCUMENT_CHUNKS_COUNT",
    "DOCUMENT_PROCESSING_LATENCY",
    "DOCUMENT_SIZE_BYTES",
    "DOCUMENT_UPLOAD_COUNT",
    "EMBEDDING_BATCH_SIZE",
    "EMBEDDING_DIMENSION",
    "EMBEDDING_LATENCY",
    "EMBEDDING_REQUEST_COUNT",
    "FACT_CHECK_CONFIDENCE",
    "FACT_CHECK_COUNT",
    "FACT_CHECK_LATENCY",
    "FACT_CHECK_VERDICT",
    "HTTP_REQUEST_COUNT",
    "HTTP_REQUEST_IN_PROGRESS",
    "HTTP_REQUEST_LATENCY",
    "HTTP_REQUEST_SIZE_BYTES",
    "HTTP_RESPONSE_SIZE_BYTES",
    "JOB_COUNT",
    "JOB_LATENCY",
    "JOB_QUEUE_SIZE",
    "JOBS_IN_PROGRESS",
    "LLM_COST",
    "LLM_LATENCY",
    "LLM_REQUEST_COUNT",
    "LLM_TOKEN_COUNT",
    "REDIS_CONNECTION_POOL_SIZE",
    "REDIS_OPERATION_COUNT",
    "REDIS_OPERATION_LATENCY",
    "REGISTRY",
    "VECTOR_SEARCH_COUNT",
    "VECTOR_SEARCH_LATENCY",
    "VECTOR_SEARCH_RESULTS",
    "counted",
    "get_metrics",
    "in_progress",
    "init_app_info",
    "init_metrics",
    "metrics_endpoint",
    "record_anki_sync",
    "record_auth_attempt",
    "record_card_generation",
    "record_card_rejection",
    "record_db_error",
    "record_db_query",
    "record_document_upload",
    "record_embedding_request",
    "record_fact_check",
    "record_http_request",
    "record_job",
    "record_llm_request",
    "record_redis_operation",
    "record_token_operation",
    "record_vector_search",
    "timed",
    "update_active_sessions",
    "update_anki_connection_status",
    "update_db_pool_metrics",
    "update_job_queue_size",
    "update_jobs_in_progress",
    # Middleware
    "CORSMiddleware",
    "RateLimitMiddleware",
    "RequestSizeLimitMiddleware",
    "RequestTracingMiddleware",
    "SecurityHeadersMiddleware",
    "add_middleware",
    "setup_middleware",
]
